version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: logistdb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U springuser -d logistdb"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  app:
    build: .
    container_name: spring-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logistdb
    restart: unless-stopped
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - app-network

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - app-network
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - sonar.web.javaOpts=-Xmx1g -Xms1g
      - sonar.ce.javaOpts=-Xmx1g -Xms1g
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - app-network

    # 2. Kibana (L'interface visuelle)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network

    # 3. Logstash (Le collecteur)
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    command: -e "input { tcp { port => 5000 codec => json_lines } } output { elasticsearch { hosts => ['elasticsearch:9200'] index => 'digital-logistics-logs-%{+YYYY.MM.dd}' } stdout { codec => rubydebug } }"
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  jenkins_home: