spring.application.name=Digital Logistics
spring.datasource.url=jdbc:postgresql://db:5432/logistdb
spring.datasource.username=springuser
spring.datasource.password=springpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=ZEdWemRHRnliM0psWVRvZ2FXVnNaQzVqYjI1MFpXUWdkR2hwY3lCaGNtZGxjeTUxY0c5emRHVmtjM1JoY21WMAo=
jwt.expiration=86400000
server.port=8083
application.default-admin.password=admin123